[supabase]
url = ""
key = ""

[llm]
api_key = "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"
model = "gpt-4.1"
provider = "openai"

[fmp]
api_key = "7fTH3lL9fJuujQAAVCTsFmIexclK7fIh"
